(define (delete pred? xs)
  (define (loop lst)
    (cond ((null? lst) '())
	  ((pred? (car lst)) (loop (cdr lst)))
	  (else (cons (car lst) (loop (cdr lst))))))
  (loop xs))

(display (delete even? '(0 1 2 3)))
(newline)
(display (delete even? '(0 2 4 6)))
(newline)
(display (delete even? '(1 3 5 7)))
(newline)
(display (delete even? '()))
